### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by nanoxd** [MosheBerman/FilterBar#1]
This project looks great! Do you intend or would you accept a pull request to add Carthage support?

**Comment by MosheBerman** [comment]
What's Carthage? 😁

**Comment by MosheBerman** [comment]
Serious question ^

**Comment by nanoxd** [comment]
[Carthage](https://github.com/Carthage/Carthage) is a simple, decentralized dependency manager for Cocoa

**Comment by MosheBerman** [comment]
I'd consider a pull request with support. Go for it.

**Comment by MosheBerman** [comment]
I would accept a PR with carthage support, sure.

**Comment by MosheBerman** [comment]
Should be supported as of 5.0.0. (I haven't set up pre-built binaries, and haven't tested it, so YMMV.)
